name: Zig Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Local Zig      
        run: curl -OJ https://ziglang.org/download/0.12.0/zig-linux-x86_64-0.12.0.tar.xz && 
          tar -xf zig-linux-x86_64-0.12.0.tar.xz  
      - name: Build with Zig
        run: ./zig-linux-x86_64-0.12.0/zig build