name: Zig Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      #- name: locale Zig
      #  run: apt-get -y install zig
      - name: Build with Zig
        run: zig build